### ISSUE TITLE
Add CohortIncidence to HADES?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortIncidence#45]
In case you'd like CohortIncidence to be part to HADES, please follow these instructions:

- Change 'master'  branch to 'main'
- Use the HADES _pkgdown.yml: https://github.com/OHDSI/DatabaseConnector/blob/main/_pkgdown.yml
- Use OhdsiRTools::fixHadesLogo() whenever regenerating the package website:   https://github.com/OHDSI/DatabaseConnector/blob/main/extras/PackageMaintenance.R#L66
- Regenerate the package website (hasn't been done since 3.0.0)
- Add "CohortIncidence is part of HADES." to the README
- Add "SystemRequirements: Java (>= 8)" to the DESCRIPTION
- Fix these notes in R Check:
  - The Title field is just the package name: provide a real title.
  - on-standard files/directories found at top level:  ‘extras’ ‘pom.xml’ (add to .Rbuildignore)
  - Package in Depends field not imported from: ‘DatabaseConnector’ (add #' @import DatabaseConnector here https://github.com/OHDSI/CohortIncidence/blob/master/R/Main.R#L21) 
  - Unexported object imported by a ':::' call: ‘jsonlite:::null_to_na’ (do you really need to call an unexported object of a 3rd-party package?)

**Comment by ablack3** [comment]
I'm wondering if any package that meets these requirements can be added to Hades. In particular if the Pare package by Maarten meets these requirements could it be added to Hades? On the last Hades call I think @schuemie decided Pare would not be added to Hades because it is not an analysis focused package which is not explicitly listed as a requirement. So the decision about what can be added feels a bit arbitrary and at the discretion of a single person. Wondering what you think @pbr6cornell. Would you expect that only "analysis focused packages" can be included in Hades?

**Comment by ablack3** [comment]
> Unexported object imported by a ':::' call: ‘jsonlite:::null_to_na’ (do you really need to call an unexported object of a 3rd-party package?)


Oh I'd concur with @schuemie in strongly cautioning against using unexported functions. If you need it the just copy the code to your package. Unexported functions are internal so their interfaces/signatures can change without warning. Does R Check allow this?

**Comment by ablack3** [comment]
Given that this package is being used for the how often study it seems natural to try to get this into Hades as it's a bar about software quality and reliability and test coverage. @schuemie could you envision a future where we have both CohortIncidence and Ed Burn's IncidencePrevalence packages in Hades or would this violate the "minimize overlapping functionality" requirement?

**Comment by chrisknoll** [comment]
Going to need some thoughts on this:

> Unexported object imported by a ':::' call: ‘jsonlite:::null_to_na’ (do you really need to call an unexported object of a 3rd-party package?)

The reason for the need is that NA and NULLS are different things in R and in order to get it to work the correct way with jsonlite we use the function of jsonlite to apply the transform the way it wants. 

I looked at the source code for this [in this issue](https://github.com/jeroen/jsonlite/issues/264), but the implementation does a call out to an internal C function, so I'm not sure I can just copy the sourcecode (I would need the underlying C impl as part of my package).

**Comment by ablack3** [comment]
Here is the definition. It looks like they are handling NaN, Inf, and -Inf (fun R special cases 😆 .  The C code is also going to be faster than R code probably. So the lapply approach is probably a bit slower and less forgiving of edge cases. 

```
/*
This function takes a list and replaces all NULL values by NA.
In addition, it will parse strings "NA" "NaN" "Inf" and "-Inf",
unless there is at least one non-na string element in the list.
In that case converting to real values has no point because
unlist() will coerse them back into a string anyway.
*/

SEXP C_null_to_na(SEXP x) {
  int len = length(x);
  if(len == 0) return x;

  //null always turns into NA
  bool looks_like_character_vector = false;
  for (int i=0; i<len; i++) {
    if(VECTOR_ELT(x, i) == R_NilValue) {
      SET_VECTOR_ELT(x, i, ScalarLogical(NA_LOGICAL));
    } else if(!looks_like_character_vector && TYPEOF(VECTOR_ELT(x, i)) == STRSXP){
      if((strcmp("NA", CHAR(STRING_ELT(VECTOR_ELT(x, i), 0))) == 0) ||
         (strcmp("NaN", CHAR(STRING_ELT(VECTOR_ELT(x, i), 0))) == 0) ||
         (strcmp("Inf", CHAR(STRING_ELT(VECTOR_ELT(x, i), 0))) == 0) ||
         (strcmp("-Inf", CHAR(STRING_ELT(VECTOR_ELT(x, i), 0))) == 0)) continue;
      looks_like_character_vector = true;
    }
  }

  // if this is a character vector, do not parse NA strings.
  if(looks_like_character_vector) return(x);

  //parse NA strings
  for (int i=0; i<len; i++) {
    if(TYPEOF(VECTOR_ELT(x, i)) == STRSXP){
      if(strcmp("NA", CHAR(STRING_ELT(VECTOR_ELT(x, i), 0))) == 0) {
        SET_VECTOR_ELT(x, i, ScalarLogical(NA_LOGICAL));
        continue;
      }
      if(strcmp("NaN", CHAR(STRING_ELT(VECTOR_ELT(x, i), 0))) == 0) {
        SET_VECTOR_ELT(x, i, ScalarReal(R_NaN));
        continue;
      }
      if(strcmp("Inf", CHAR(STRING_ELT(VECTOR_ELT(x, i), 0))) == 0) {
        SET_VECTOR_ELT(x, i, ScalarReal(R_PosInf));
        continue;
      }
      if(strcmp("-Inf", CHAR(STRING_ELT(VECTOR_ELT(x, i), 0))) == 0) {
        SET_VECTOR_ELT(x, i, ScalarReal(R_NegInf));
        continue;
      }
    }
  }

  //return updated list
  return x;
}

```

**Comment by ablack3** [comment]
Since you're importing rlang you can use the coalesce operator for free.

``` r
library(rlang)
lst <- list(1, 2, NULL, NA, NaN, Inf, -Inf)
jsonlite:::null_to_na(lst)
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 2
#> 
#> [[3]]
#> [1] NA
#> 
#> [[4]]
#> [1] NA
#> 
#> [[5]]
#> [1] NaN
#> 
#> [[6]]
#> [1] Inf
#> 
#> [[7]]
#> [1] -Inf
lapply(lst, \(x) x %||% NA)
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 2
#> 
#> [[3]]
#> [1] NA
#> 
#> [[4]]
#> [1] NA
#> 
#> [[5]]
#> [1] NaN
#> 
#> [[6]]
#> [1] Inf
#> 
#> [[7]]
#> [1] -Inf
```

<sup>Created on 2023-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by chrisknoll** [comment]
Thanks for looking...my initial instinct was correct: to use the jsonlite implementation because they're doing additional work (such as handling Inf, -Inf) which we didn't recognize without looking at the actual implementation.

I'm fine using the implementation `\(x) x %||% NA` but I'd like to know the new R requirements:  the `\(x)` is a new syntax I think in 4.1 for function expression...but is `%||%` something else introduced in R 4.x?  I'm not fluent in R and would like the code readable, and the above to me seems a little hard to understand (ie: how is it handling the `Inf` cases in this by converting nulls to NA but leaving Inf alone)/

**Comment by chrisknoll** [comment]
The call to `jsonlite:::null_to_na` is happening [here](https://github.com/OHDSI/CohortIncidence/blob/4e9df6438cfa6bfd6cb87f8ea1f4461be04655b8/R/Classes.R#L946).

The root of this call is from a function called [`.convertJSON()`](https://github.com/OHDSI/CohortIncidence/blob/4e9df6438cfa6bfd6cb87f8ea1f4461be04655b8/R/Classes.R#L936C1-L936C13) which attempts to read in a JSON string and remove NA elements from it (the root of a parsed json string is a list of lists. It recursively goes through removing elements that have null values and replace them with NA...I believe because list elements that are 'null' values vs vectors that have a 'null' value in it are treated different, and so we convert everything over to NA before parsing out the values of the JSON into the R6 Class State.

So, to put it shortly, I think replacing that call to jsonlite:::nullToNa with your call, and I think it's safe to assume that it will always be a list as an input because there's an if statement checking if the element is a list then make the nullToNa call, else you just return the element value itself.

**Comment by ablack3** [comment]
.nullToNa Looks like a recursive function. It would be good to have some test cases for that. Anyway I think there's an alternative to that internal function. You can still use the internal json lite function but just know it could break without warning.

**Comment by schuemie** [comment]
@chrisknoll : did you have a chance to work on this?

**Comment by chrisknoll** [comment]
I haven't, sorry.   I can look into this in the next few days.

**Comment by chrisknoll** [comment]
I'm starting the branch: [hades-requirements](https://github.com/OHDSI/CohortIncidence/tree/hades-updates) to collect the changes needed for this issue.  Feel free to make commits on that branch if you want to jump in, but the first thing I'll be working on is the nullToNa logic discussed above.

**Comment by chrisknoll** [comment]
@ablack3 , question about the mechanics of this code:

```
lst <- lapply(lst, function(x) if (is.null(x)) NA else x)
```

here, we're reassigning lst to a new list, but that is only in the context of this call. and I believe the way R works is that you modify the list, and you get a new list.  I think what this usecase calls for, tho, is an 'in-place update' of the list elements.   I think this is important because we are getting the list-of-lists as input and we're going through the elements and reassigning null to NA.   do you think this is why the C++ approach was performed because it will execute the update on the variable directly?

**Comment by chrisknoll** [comment]
You can check this PR #51 for the requested changes.

Thanks to @schuemie for the task list.

**Comment by schuemie** [comment]
Great! Would it be possible to rename master to main?

**Comment by schuemie** [comment]
I'm sorry, but as long as the principal branch isn't called 'main' I can't add this package to HADES. All HADES package management code assumes 'main' and would break.

**Comment by chrisknoll** [comment]
Main branch created, your tools should work fine.

**Comment by schuemie** [comment]
Thanks! Just be aware that your [GitHub pages](https://github.com/OHDSI/CohortIncidence/settings/pages) currently points to the master branch, so make sure to always keep master and main in sync, or your documentation won't match the released version.

I highly recommend making main your principle branch.

**Comment by schuemie** [comment]
Also note that `install_github()` will install from the principal branch, so again, please make sure that master and main are always exactly in sync.
