### ISSUE TITLE
It is unclear from the documentation where the demoCohortSchema.cohort comes from.  

### ISSUE THREAD

**Issue by greshje** [OHDSI/CohortIncidence#53]
Using the documentation from https://ohdsi.github.io/CohortIncidence/articles/using-cohortincidence.html it is unclear what to use for the demoCohortSchema.cohort or how it is created.  

![image](https://github.com/OHDSI/CohortIncidence/assets/36824929/806c6e8e-b292-4554-9b23-60368bc10924)

**Comment by chrisknoll** [comment]
That is the name of their cohort table.   The documentation has no idea about how it was named or where the name came from, so this is just a placeholder.

In order to use the CohortIncidence package, there is some basic understanding of OHDSI concepts that are going to be necessary in order to understand how those concepts are applied in the tools.  I suggest looking into the Book of OHDSI which will describe cohorts, the CDM, and other key concepts that are referenced across our standardized tools.
