### ISSUE TITLE
How do I use existing cohort definitions to run CohortIncidence and request for clairification on parameters.  

### ISSUE THREAD

**Issue by greshje** [OHDSI/CohortIncidence#54]
Using the documentation from https://ohdsi.github.io/CohortIncidence/articles/using-cohortincidence.html I'm not sure of what the startWith, endWith, and endoffset, and cleanWindow are for.  For example, I have two target cohorts: homeless and not-homeless and one outcome cohort: vaccinated.  How do I use these existing cohort definitions to define the cohorts here?  I'm also running this in Strategus.  I can get results for the HowOften studies, but when I try to run the cohorts I have defined I get zero records back.  

Also, what is id used for v. cvohortId?  What is the tars list?

**Comment by chrisknoll** [comment]
API reference is [here](https://ohdsi.github.io/CohortIncidence/reference/index.html).

`startWith` and `endWith` defines Time At Risk, documented [here](https://ohdsi.github.io/CohortIncidence/reference/createTimeAtRiskDef.html).
`cleanWindow` is used in Outcome definitions, documented [here](https://ohdsi.github.io/CohortIncidence/reference/createOutcomeDef.html)

> Also, what is id used for v. cvohortId?

Not sure what v. cvohortId is.

> What is the tars list?

It it is the list of Time At Risk definitions in your IncidenceRate [design ](https://ohdsi.github.io/CohortIncidence/reference/createIncidenceDesign.html).  A IR Design consistes of a list of Analyses, and each Analyses represents a the Target, Outcome, and TimeAtRisks that should be calculated, where each T is paired with each O paired with each TAR.  An analysis with 3 Ts, 2 Os, and 2 TARS will produce 3x2x2 = 12 incidence rates.

> I have two target cohorts: homeless and not-homeless and one outcome cohort: vaccinated. How do I use these existing cohort definitions to define the cohorts here?

If you look at the [example code](https://ohdsi.github.io/CohortIncidence/articles/using-cohortincidence.html), you will define two target populations using your cohortIDs for your two target populations of homless and non-homeless.  You define your outcome using the cohort ID of your vaccinated populatin, and you specify a 'clean window' in your outcome if you want to consider sime time after your outcome excluded from at-risk.  You may want to specify a 9999 clean window because after you become vaccinated, you can't become vaccinated again, so all time after vaccination you are not at risk again.  Or maybe you don't want to exclude all time after, and instead set up a 30d clean window after vaccination. It's up to you based on how you are designing your study.

Finally, you need to specify your time at risks:  what time relative to your start/ending of homless/not-homeless are you going to be looking for the outcome of vaccination?

After you have your T, O, and TAR specified, you create your analysis specfying that you want to use both Ts, the O and the TAR in it, and you add that to your IncidenceDesign.

The other question about why you get zero records, that's a question outside the scope of CohortIncidence package.
